main: de.breidenbach.uhc.MinecraftUHC
name: MinecraftUHC
version: 1.0
author: Peter Breidenbach

commands:
  uhc:
    description: Set up the Server for a UHC match
    usage: /<command> {start | setup}
