main: de.breidenbach.uhc.MinecraftUHC
name: MinecraftUHC
version: 1.0
author: Peter Breidenbach

commands:
  setup:
    description: Set up the Server for a UHC match
    usage: /<command>
  start:
    description: Start the match
    usage: /<command>
  stop:
    description: Cancels a match
    usage: /<command>
